<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x82\x03\x0A\x10helloworld.proto\x12\x0Ahelloworld\"\x1C\x0A\x0CHelloRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\"\x1D\x0A\x0AHelloReply\x12\x0F\x0A\x07message\x18\x01 \x01(\x092\xE4\x01\x0A\x07Greeter\x12>\x0A\x08SayHello\x12\x18.helloworld.HelloRequest\x1A\x16.helloworld.HelloReply\"\x00\x12K\x0A\x13SayHelloStreamReply\x12\x18.helloworld.HelloRequest\x1A\x16.helloworld.HelloReply\"\x000\x01\x12L\x0A\x12SayHelloBidiStream\x12\x18.helloworld.HelloRequest\x1A\x16.helloworld.HelloReply\"\x00(\x010\x01B6\x0A\x1Bio.grpc.examples.helloworldB\x0FHelloWorldProtoP\x01\xA2\x02\x03HLWb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

